name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: download toolchain
      run: wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2019q4/RC2.1/gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2 
    - name: extract
      run: tar -xjvf gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2
    - name: export
      run: export PATH=$GITHUB_WORKSPACE/gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux/bin/:$PATH
    - name: test gcc
      run: arm-none-eabi-gcc --version 
    - name: make 
      run: make 
